name:  Code Checks

on:  push

jobs:
  greeting:
    runs-on:  ubuntu-latest
    steps:
      - name:  Greetings!
        run:  echo hello world

  run-python-tests:
    runs-on:  ubuntu-latest
    steps:  
      -  uses:  actions/checkout@v3

      - name: Install packages
        run: python - m pip install -e ".[test]"

      - name: 
